cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git zlib1g-dev zip unzip libjpeg-dev libpng-dev libxml2-dev libzip-dev -yqq

# Install mysql-driver and pcov
- pecl install pcov
- docker-php-ext-enable pcov
- docker-php-ext-install pdo_mysql
- docker-php-ext-install gd
- docker-php-ext-install exif
- docker-php-ext-install zip


# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install --prefer-dist
# - touch storage/testing.sqlite
# - php artisan migrate --database=sqlite_testing --force

stages:
  - test

# Test on PHP 7.4
test74:
  image: php:7.4
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testdox

# Test on PHP 8.0
test74:
  image: php:8.0
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testdox